"""add_google_credentials

Revision ID: 533983454fa0
Revises: a9f58435a020
Create Date: 2026-04-21 16:57:54.066675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533983454fa0'
down_revision: Union[str, Sequence[str], None] = 'a9f58435a020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_db_credentials', sa.Column('google_credentials', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_db_credentials', 'google_credentials')
    # ### end Alembic commands ###
