"""initial_auto_schema

Revision ID: a9f58435a020
Revises: 
Create Date: 2026-04-21 16:50:03.426003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a9f58435a020'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('active_modules', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_telegram_chat_id'), 'tenants', ['telegram_chat_id'], unique=True)
    op.create_index(op.f('ix_tenants_whatsapp_number'), 'tenants', ['whatsapp_number'], unique=True)
    op.create_table('tenant_db_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('db_type', sa.String(length=32), nullable=False),
    sa.Column('connection_url', sa.Text(), nullable=False),
    sa.Column('schema_blueprint', sa.Text(), nullable=True),
    sa.Column('ssl_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_db_credentials_tenant_id'), 'tenant_db_credentials', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_db_credentials_tenant_id'), table_name='tenant_db_credentials')
    op.drop_table('tenant_db_credentials')
    op.drop_index(op.f('ix_tenants_whatsapp_number'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_telegram_chat_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
